<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="engineering" nsURI="urn:org.nasdanika.engineering" nsPrefix="org.nasdanika.engineering">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/engineering.md"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/model-element.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="path"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources associated with the element, e.g. documentation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//NamedElement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Resources associated with the element, e.g. documentation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentation" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableOfContents" eType="#//TableOfContents"
        containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//Document" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sections for model element descriptions. In documents sections apply to the document content, i.e. document descriptions cannot have sections. Sections can be nested."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" upperBound="-1"
        eType="ecore:EClass ../../org.nasdanika.diagram/model/diagram.ecore#//Diagram"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Pluggable representations of a model element, e.g. a component diagram for engineers and modules."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableOfContents">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/table-of-contents.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Table of contents role defines where it is positioned on the page. &#xA;See [Appearance](Appearance.html) for details regarding page parts.&#xA;One of the following:&#xA;&#xA;* ``content`` - in the content panel, before the document/section text.&#xA;* ``content-left`` - Left content panel.&#xA;* ``content-right`` - Right content panel.&#xA;* ``float-left`` - Floats to the left. Diferent from ``content-left`` which takes the entire column.&#xA;* ``float-right`` - Floats to the right. Different from ``content-right`` which takes the entire column.&#xA;"/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Table of contents depth. Zero (default) means unlimited depth."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Table of contents header, e.g. ``Contents``. No header by default."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" eSuperTypes="#//ModelElement ../../org.nasdanika.ncore/model/ncore.ecore#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/named-element.md"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//NamedElement ../../org.nasdanika.ncore/model/ncore.ecore#//Temporal">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/event.md"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alignable" abstract="true" interface="true">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/alignable.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aligns" upperBound="-1"
        eType="#//Alignment" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Aims to which this alignable aligns. E.g. a module level principle may align to organization pirinciples."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endeavor" eSuperTypes="#//ModelElement ../../org.nasdanika.ncore/model/ncore.ecore#//Period #//Alignable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="capacity children"/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/endeavor.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number between 0 and 1."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benefit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number representing benefit of this endeavor. Can be explicitly provided or derived."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Total cost of the endeavor includes both cost and labor multiplied by rate."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="#//Engineer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer responsible for completion of this endeavor. For a simple issue it would be an engineer working on the issue, for other endeavors the assignee's may not actually work on issues, but rather coordinate. E.g. [increment](Increment.html) assignee responsibility would be similar to those of a [scrum master](https://en.wikipedia.org/wiki/Scrum_(software_development)#Scrum_master)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allIssues" upperBound="-1"
        eType="#//Issue" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues scheduled to work on in this increment directly or indirectly via [releases](Release.html) and [features](Feature.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacity" upperBound="-1"
        eType="#//Capacity" changeable="false" derived="true" eOpposite="#//Capacity/endeavor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="[Capacity](Capacity.html) or [Allocation](Allocation.html).  If an element is capacity that means that there is a capacity for an [engineer](Engineer.html) to work on this endeavor.  If an element is allocation that means that Engineer's capacity has been allocated to work on a particular [engineered element](EngineeredElement.html) [issues](Issue.html) in a particular [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" upperBound="-1"
        eType="#//Objective" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Assignee's objectives for this endeavor."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedObjectives" upperBound="-1"
        eType="#//Objective" derived="true" eOpposite="#//Objective/endeavor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Objectives defined under [Engineer](Engineer.html) for this endeavor."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allObjectives" upperBound="-1"
        eType="#//Objective" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="All objectives for this endeavor - a union of objectives and linkedObjectives."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Increment" eSuperTypes="#//NamedElement #//Endeavor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nesting"/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="icon" value="far fa-calendar-alt"/>
      <details key="documentation-reference" value="doc/increment.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Increment" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Increment children, e.g. quarters for a year or months for a quarter."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/increment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues scheduled to work on in this increment"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" changeable="false" derived="true" eOpposite="#//Release/increment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Releases scheduled to be made available in this increment"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IssueCategory" eSuperTypes="#//Aim">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/issue-category.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Category relative importance. Can be used to allocate issues to increments in a balanced way."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues in the category."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="categories"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cumulative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, unused category weight &quot;capacity&quot; is carried over to future increments and overused is subtracted from future increments. This allow low-weight categories to accumulate weight over time."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocations" upperBound="-1"
        eType="#//Allocation" changeable="false" derived="true" eOpposite="#//Allocation/category">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allocations for this category."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//IssueCategory" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue categories can form a hierarchy."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IssueStatus" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/issue-status.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues in this status."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="done" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If ``true``, indicates that the issue in this status is successfully completed and issues requiring is are now workable. Issue can be completed (completion = 1), but not done, e.g. it can be cancelled."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IssuePriority" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/issue-priority.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues in this priority"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IssueSeverity" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/issue-severity.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues in this severity."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Issue" eSuperTypes="#//EngineeredCapability">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/issue.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="increment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Issue" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues can be infinitely nested to form a [Work Breakdown Structure](https://en.wikipedia.org/wiki/Work_breakdown_structure)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//Capability">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Capabilities required to start working on an issue."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="requiredBy"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="increment" eType="#//Increment"
        eOpposite="#//Increment/issues">
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="issues"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Increment for which this issue is directly scheduled. Issue can be scheduled for an increment directly or indirectly via [features](Feature.html) and [releases](Release.html). Release increment can be different from issue incrmenent. E.g. issue can be scheduled for May, but its release might be scheduled for July."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributesTo" upperBound="-1"
        eType="#//Feature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue can contribute to zero or more features."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="issues"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
        eType="#//Note" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue notes are used for discussion and to record progress, remaining effort, and issue status if it is not set at the issue level. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//IssueCategory">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue category."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//EngineeredElement"
        changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Target element for this issue - container of the issue itself or the root issue in the issue hierarchy."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//IssueStatus">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue status."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="issues"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue is workable if it doesn't have any unavailable required capabilities."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" eOpposite="#//Release/issues">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue can be planned for zero or more releases directly. It can be also indirectly planned for releases via contribution to [features](Feature.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Effort for this issue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Monetary cost for this issue, e.g. cost of materials."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingEffort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Remaining effort is computed from issue effort and [notes](Note.html) effort or remaining effort."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Remaining cost is computed from issue cost and [notes](Note.html) cost or remaining cost."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priority" eType="#//IssuePriority">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue status."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="issues"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="severity" eType="#//IssueSeverity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue status."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="issues"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/note.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//Engineer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Note author."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Note date and time."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Effort spent."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Cost spent."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingEffort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If remaining effort is not specified explicitly is it computed from by subtracting note effort from the issue remaining effort. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If remaining cost is not specified explicitly is it computed from by subtracting note cost from the issue remaining cost. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//IssueStatus">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If issue status is not set explicitly the the status of the last note with status is used as issue status. It can be used to keep track of status changes."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Forum" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/forum.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discussion" upperBound="-1"
        eType="#//Forum" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sub-forums."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
        eType="#//Topic" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Discussion topics in this forum."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EngineeredElement" abstract="true" eSuperTypes="#//Forum ../../org.nasdanika.ncore/model/ncore.ecore#//Period">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/engineered-element.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="capacity"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues (work items) for this element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owners" upperBound="-1"
        eType="#//Engineer" eOpposite="#//Engineer/owns">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element owners have both expertise and authority over the element."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="experts" upperBound="-1"
        eType="#//Engineer" eOpposite="#//Engineer/expertise">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Experts have expertise with the element, but no authority. E.g. they can help others with using the element, but cannot make changes in the element without owners' approval."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocations" upperBound="-1"
        eType="#//Allocation" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allocations of [engineer](Engineer.html)'s [capacity](Capacity.html) to work on this engineered element [issues](Issue.html) for a particular [endeavor](Endeavor.html) and [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="principles" upperBound="-1"
        eType="#//Principle" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Principles associated with this element to support decision making."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allIssues" upperBound="-1"
        eType="#//Issue" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues (work items) for this element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/document.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Document/section content in HTML."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markdownContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Document/section content in [Markdown](https://en.wikipedia.org/wiki/Markdown)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Persona" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/persona.md"/>
      <details key="icon" value="far fa-user"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Persona goals are used to elicit and align [endeavors](Endeavor.html). E.g. new [product](Product.html) [features](Feature.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representatives" upperBound="-1"
        eType="#//Engineer" eOpposite="#//Engineer/represents">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineers which represent this persona. E.g. in a hierarchical [organization](Organization.html) some units or engineers may build products for internal customers - other units or engineers. In this case some of those internal customers act as persona representatives and work with the persona owner to identify persona goals and product features to address those goals. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//Persona" eOpposite="#//Persona/extensions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A persona may extend another persona. E.g. &quot;Moderator&quot; discussion forum persona extends &quot;User&quot; persona, which may in turn extend &quot;Visitor&quot; persona. This persona inherits goals for the extended personas."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//Persona" changeable="false" derived="true" eOpposite="#//Persona/extends">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Personas extending this persona."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engineer" eSuperTypes="#//Persona">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/engineer.md"/>
      <details key="icon" value="fas fa-user"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="capacity start_end"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Modules ([products](Product.html)) are defined under engineer or [organization](Organization.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" upperBound="-1" eType="#//EngineeredElement"
        changeable="false" derived="true" eOpposite="#//EngineeredElement/owners">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineered elements owned by this engineer."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expertise" upperBound="-1"
        eType="#//EngineeredElement" changeable="false" derived="true" eOpposite="#//EngineeredElement/experts">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineered element which this engineer has experience with."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="increments" upperBound="-1"
        eType="#//Increment" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Increments are defined under engineer/[organization](Organization.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//journey/Activity" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer may perform shared activities (services) which can be parts of [persona](Persona.html) [journeys](Journey.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personas" upperBound="-1"
        eType="#//Persona" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Personas which this engineer/[organization](Organization.html) builds products for."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Endeavor" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer assignments."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="assignee"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issueCategories" upperBound="-1"
        eType="#//IssueCategory" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue categories are defined under engineer/[organization](Organization.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issueStatuses" upperBound="-1"
        eType="#//IssueStatus" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue statuses are defined under engineer/[organization](Organization.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issuePriorities" upperBound="-1"
        eType="#//IssuePriority" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue priorities are defined under engineer/[organization](Organization.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issueSeverities" upperBound="-1"
        eType="#//IssueSeverity" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issue severities are defined under engineer/[organization](Organization.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Default engineer rate. Can be customized in capacity."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designations" upperBound="-1"
        eType="#//Allocation" changeable="false" derived="true" eOpposite="#//Allocation/engineer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allocations of this [engineer](Engineer.html)'s [capacity](Capacity.html) to work on an [engineered element](EngineeredElement.hml) [issues](Issue.html) for a particular [endeavor](Endeavor.html) and [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacity" upperBound="-1"
        eType="#//Capacity" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer's capacity for a particular [endeavor](Endeavor.html)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="represents" upperBound="-1"
        eType="#//Persona" changeable="false" derived="true" eOpposite="#//Persona/representatives">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Personas which this engineer represents."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" changeable="false" derived="true" eOpposite="#//Message/author">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Discussion messages authored by this engineer."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectives" upperBound="-1"
        eType="#//Objective" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer's objectives for a particular [endeavor](Endeavor.html)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Organization" eSuperTypes="#//Engineer">
    <eAnnotations source="urn:org.nasdanika">
      <details key="icon" value="far fa-building"/>
      <details key="documentation-reference" value="doc/organization.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="engineers" upperBound="-1"
        eType="#//Engineer" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="icon" value="fas fa-users"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Members of this organization."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/module.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sub-modules of this module."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Module">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Modules which this module depends on."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependants" upperBound="-1"
        eType="#//Module" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Derived opposite to dependencies - modules which depend on this module."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="dependencies"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Module">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/product.md"/>
      <details key="type-code" value="d"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Product releases."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Product features."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability" eSuperTypes="#//NamedElement ../../org.nasdanika.ncore/model/ncore.ecore#//Period">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/capability.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//Issue" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues requiring this capability."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="requires"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="available" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that this capability is available and [issues](Issue.html) which require it are workable, unless they have other unavailable requirements."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EngineeredCapability" eSuperTypes="#//Capability #//Endeavor">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/engineered-capability.md"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Release" eSuperTypes="#//EngineeredCapability">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/release.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="increment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="increment" eType="#//Increment"
        eOpposite="#//Increment/releases">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Increment for which this release is scheduled."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" changeable="false" derived="true" eOpposite="#//Feature/releases">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Features planned for this release."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/releases">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues planned for this release."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//EngineeredCapability">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/feature.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" eOpposite="#//Release/features">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Releases for which this feature is planned."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues contributing to this feature."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Feature" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Features can be organized into a hierarchy."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directory" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/directory.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//NamedElement" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Directory elements."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capacity" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/capacity.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endeavor" lowerBound="1"
        eType="#//Endeavor" eOpposite="#//Endeavor/capacity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Endeavor for which containing [engineer](Engineer.html) has this capacity for."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For capacitly - amount of effort which the containing [engineer](Engineer.html) can spend on the capacity's [endeavor](Endeavor.html). For allocation - amount of effort which allocation's engineer can spend on the containing [engineered element](EngineeredElement.html) and, optionally, [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="funds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For capacitly - monetary amount which the containing [engineer](Engineer.html) can spend on the capacity's [endeavor](Endeavor.html). For allocation - monetary amount which allocation's engineer can spend on the containing [engineered element](EngineeredElement.html) and, optionally, [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For effort capacity, containing [engineer](Engineer.html) rate, if different from the engineer's default rate."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation" eSuperTypes="#//Capacity">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/allocation.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="engineer" lowerBound="1"
        eType="#//Engineer" eOpposite="#//Engineer/designations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer whose capacity is allocated to work on the containing [engineered element](EngineeredElement.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="#//IssueCategory"
        eOpposite="#//IssueCategory/allocations">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Optional issue category for this allocation. E.g. a allocation can be made to &quot;Documentation&quot; or &quot;Test coverage&quot; categories."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aim" eSuperTypes="#//NamedElement #//Alignable">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/aim.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignments" upperBound="-1"
        eType="#//Alignment" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Alignments to this aim. "/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="aim"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Principle" eSuperTypes="#//Aim">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/principle.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Principle" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Principles can be nested. E.g. Architectural Principles may contain Data Architecture principles."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alignment" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/alignment.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aim" eType="#//Aim">
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Aim to which the containing element, e.g. [endeavor](Endeavor.html) aligns."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Alignment weight can be used with [Objective](Objective.html) and [KeyResult](KeyResult.html) aims to indicate how much the containing endeavor contributes to completion of the aim."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Aim">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/goal.md"/>
      <details key="icon" value="fas fa-bullseye"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Goal" containment="true" eKeys="#//ModelElement/path">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="[Persona](Persona.html) goals can be nested."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/message.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Date/time when this message was posted."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//Engineer"
        eOpposite="#//Engineer/messages">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Message author."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic" eSuperTypes="#//Message">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/topic.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="#//Message" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Messages in this topic."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElementReference" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/named-element-reference.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference target"/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/link.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Target URL"/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyResult" eSuperTypes="#//Aim">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/key-result.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates how much this key result or [objective](Objective.html) contributes to completion of the containing or parent objective."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number between 0 and 1. Computed from alignments for key results and for alignments, key results, and sub-objectives for [objectives](Objective.html)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initiatives" upperBound="-1"
        eType="#//Issue" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="What needs to be done to achieve the containing Key Result."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objective" eSuperTypes="#//KeyResult">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/objective.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endeavor" eType="#//Endeavor"
        eOpposite="#//Endeavor/linkedObjectives">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Endeavor for which containing [engineer](Engineer.html) has this objective for. E.g. &quot;Achieve XYZ in Q2&quot;. Objectives can also be contained in endeavors directly. In this case they are assumed to be objectives of the assignee."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyResults" upperBound="-1"
        eType="#//KeyResult" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Key results for this objective."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Objective" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sub-objectives of this objective."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Objective">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Objective can be linked to a parent objective it is not already a child of objective, i.e. is contained by an [engineer](Engineer.html) or [endeavor](Endeavor.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedObjectives" upperBound="-1"
        eType="#//Objective" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Objectives linked to this one via the ``parent`` reference."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="opposite" value="parent"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subObjectives" upperBound="-1"
        eType="#//Objective" changeable="false" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A union of children and linked objectives."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision" eSuperTypes="#//Issue #//Aim">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/decision.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Date when this decision goes into effect once it is available (done). If not set, decision goes into effect once it is in a done status."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Date when decision stops being in effect if it was in effect before. If not set, the decision is effective indefinitely if it is in a done status."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supercedes" upperBound="-1"
        eType="#//Decision" eOpposite="#//Decision/supercededBy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Decisions which this decision supercedes once (if ever) it goes into effect."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supercededBy" upperBound="-1"
        eType="#//Decision" changeable="false" derived="true" eOpposite="#//Decision/supercedes">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Decisions which (will) supercede this decision when (if ever) they are effective."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Documentation of what has been decided (decision process outcome)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="journey" nsURI="urn:org.nasdanika.engineering.journey" nsPrefix="org.nasdanika.engineering.journey">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/journey/package-summary.md"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Activity">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/flow/activity.md"/>
      </eAnnotations>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.flow/model/flow.ecore#//Activity">
        <eTypeArguments eClassifier="#//journey/Activity"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Journey" eSuperTypes="../../org.nasdanika.flow/model/flow.ecore#//Flow">
      <eAnnotations source="urn:org.nasdanika">
        <details key="documentation-reference" value="doc/flow/journey.md"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="final abstract elements"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
