<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="engineering" nsURI="urn:org.nasdanika.engineering" nsPrefix="org.nasdanika.engineering">
  <eAnnotations source="urn:org.nasdanika">
    <details key="documentation-reference" value="doc/engineering.md"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Adaptable" instanceClassName="org.nasdanika.common.Adaptable"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="#//Adaptable">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/model-element.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element's unique ID. Derived from element type and containment path (parent ID)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element's path to form full element URL. Shall be unique in the containing collection. If blank, derived from element's position in the collection or from the local ID. For named elements can be derived from element name.&#xA;Element URL is formed by adding ``.html`` extension to the path if the model element's EClass doesn't have containment references and as such the element may not have children, and by adding ``/index.html`` otherwise."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="load-key" value="path"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Description in HTML."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="markdownDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Description in markdown."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//NamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/named-element.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element name."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endeavor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="start_end capacity"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="completion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benefit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="#//Engineer"
        eOpposite="#//Engineer/assignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allIssues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues scheduled to work on in this increment directly or indirectly via releases and features."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacity" upperBound="-1"
        eType="#//Capacity" changeable="false" derived="true" eOpposite="#//Capacity/endeavor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="[Capacity](Capacity.html) or [Allocation](Allocation.html).  If an element is capacity that means that there is a capacity for an [engineer](Engineer.html) to work on this endeavor.  If an element is allocation that means that Engineer's capacity has been allocated to work on a particular [engineered element](EngineeredElement.html) [issues](Issue.html) in a particular [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Increment" eSuperTypes="#//NamedElement #//Endeavor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nesting"/>
    </eAnnotations>
    <eAnnotations source="urn:org.nasdanika">
      <details key="icon" value="far fa-calendar-alt"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Increment" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/increment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues scheduled to work on in this increment"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" changeable="false" derived="true" eOpposite="#//Release/increment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Releases scheduled to be made available in this increment"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IssueCategory" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Category relative importance. Can be used to allocate issues to increments in a balanced way."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/category">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues in the category."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cumulative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, unused category weight &quot;capacity&quot; is carried over to future increments and overused is subtracted from future increments. This allow low-weight categories to accumulate weight over time."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocations" upperBound="-1"
        eType="#//Allocation" changeable="false" derived="true" eOpposite="#//Allocation/category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IssueStatus" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/status">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues in this status."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="done" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Issue" eSuperTypes="#//EngineeredCapability">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/issue.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="increment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Issue" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//Capability" eOpposite="#//Capability/requiredBy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Capabilities required to start working on an issue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="increment" eType="#//Increment"
        eOpposite="#//Increment/issues">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contributesTo" upperBound="-1"
        eType="#//Feature" eOpposite="#//Feature/issues"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notes" upperBound="-1"
        eType="#//Note" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="#//IssueCategory"
        eOpposite="#//IssueCategory/issues">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//EngineeredElement"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//IssueStatus"
        eOpposite="#//IssueStatus/issues">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" eOpposite="#//Release/issues">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingEffort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        changeable="false" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Note" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//Engineer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingEffort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" eType="#//IssueStatus">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EngineeredElement" abstract="true" eSuperTypes="#//NamedElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/engineered-element.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="capacity"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owners" upperBound="-1"
        eType="#//Engineer" eOpposite="#//Engineer/owns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="experts" upperBound="-1"
        eType="#//Engineer" eOpposite="#//Engineer/expertise"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocations" upperBound="-1"
        eType="#//Allocation" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allocations of [engineer](Engineer.html)'s [capacity](Capacity.html) to work on this engineered element [issues](Issue.html) for a particular [endeavor](Endeavor.html) and [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="principles" upperBound="-1"
        eType="#//Principle" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Persona" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/persona.md"/>
      <details key="icon" value="far fa-user"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" changeable="false" derived="true" eOpposite="#//Activity/personas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representatives" upperBound="-1"
        eType="#//Engineer" eOpposite="#//Engineer/represents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" upperBound="-1"
        eType="#//Persona" eOpposite="#//Persona/extensions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extensions" upperBound="-1"
        eType="#//Persona" changeable="false" derived="true" eOpposite="#//Persona/extends"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engineer" eSuperTypes="#//Persona">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/engineer.md"/>
      <details key="icon" value="fas fa-user"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="capacity"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" upperBound="-1" eType="#//EngineeredElement"
        changeable="false" derived="true" eOpposite="#//EngineeredElement/owners"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expertise" upperBound="-1"
        eType="#//EngineeredElement" changeable="false" derived="true" eOpposite="#//EngineeredElement/experts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="increments" upperBound="-1"
        eType="#//Increment" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personas" upperBound="-1"
        eType="#//Persona" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Endeavor" changeable="false" derived="true" eOpposite="#//Endeavor/assignee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issueCategories" upperBound="-1"
        eType="#//IssueCategory" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issueStatuses" upperBound="-1"
        eType="#//IssueStatus" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="designations" upperBound="-1"
        eType="#//Allocation" changeable="false" derived="true" eOpposite="#//Allocation/engineer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allocations of this [engineer](Engineer.html)'s [capacity](Capacity.html) to work on an [engineered element](EngineeredElement.hml) [issues](Issue.html) for a particular [endeavor](Endeavor.html) and [issue category](IssueCategory.html)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capacity" upperBound="-1"
        eType="#//Capacity" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Engineer's capacity for a particular [endeavor](Endeavor.html)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="represents" upperBound="-1"
        eType="#//Persona" changeable="false" derived="true" eOpposite="#//Persona/representatives"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Organization" eSuperTypes="#//Engineer">
    <eAnnotations source="urn:org.nasdanika">
      <details key="icon" value="far fa-building"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="engineers" upperBound="-1"
        eType="#//Engineer" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="icon" value="fas fa-users"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/module.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Module">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/product.md"/>
      <details key="type-code" value="d"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Product journeys define how to use a particular product and its features."/>
      </eAnnotations>
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/requires">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues requiring this capability."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="available" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EngineeredCapability" eSuperTypes="#//Capability #//Endeavor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aligns" upperBound="-1"
        eType="#//Alignment" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Release" eSuperTypes="#//EngineeredCapability">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/release.md"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="increment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="increment" eType="#//Increment"
        eOpposite="#//Increment/releases"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" changeable="false" derived="true" eOpposite="#//Feature/releases">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Features made available in this release."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/releases">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues closed in this release."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//EngineeredCapability">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/feature.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//Release" eOpposite="#//Release/features"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Activities using this feature."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issues" upperBound="-1"
        eType="#//Issue" changeable="false" derived="true" eOpposite="#//Issue/contributesTo">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Issues contributing to this feature."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/activity.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personas" upperBound="-1"
        eType="#//Persona" eOpposite="#//Persona/activities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activityType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Pseudo-activity (stereo)type. One of:&#xA;&#xA;* choice&#xA;* fork&#xA;* join&#xA;* entryPoint&#xA;* exitPoint&#xA;* inputPin&#xA;* outputPin&#xA;* expansionInput&#xA;* expansionOutput&#xA;* end&#xA;&#xA;Pseudo-activities name is not shown on the diagram, they are not clickable, and they are not listed as journey children.&#xA;&#xA;See [PlantUML State Diagram](https://plantuml.com/state-diagram) for more details."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deliverables" upperBound="-1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1"
        eType="#//Call" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Product features used by this activity."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Journey" eSuperTypes="#//Activity">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/journey.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If true, journey is visualized as a composite state on its parent journey diagram. If false, it is visualized as a simple state."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/transition.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Activity">
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payload" upperBound="-1"
        eType="#//Artifact"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Description in markdown."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" upperBound="-1"
        eType="#//Artifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" eSuperTypes="#//EngineeredElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="../doc/artifact.md"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directory" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//NamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capacity" eSuperTypes="#//ModelElement">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/capacity.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endeavor" lowerBound="1"
        eType="#//Endeavor" eOpposite="#//Endeavor/capacity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="funds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation" eSuperTypes="#//Capacity">
    <eAnnotations source="urn:org.nasdanika">
      <details key="documentation-reference" value="doc/allocation.md"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="engineer" lowerBound="1"
        eType="#//Engineer" eOpposite="#//Engineer/designations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" upperBound="-1"
        eType="#//IssueCategory" eOpposite="#//IssueCategory/allocations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aim" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignments" upperBound="-1"
        eType="#//Alignment" derived="true" eOpposite="#//Alignment/aim"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aligns" upperBound="-1"
        eType="#//Alignment" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
        <details key="strict-containment" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Principle" eSuperTypes="#//Aim">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Principle" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alignment" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aim" eType="#//Aim" eOpposite="#//Aim/alignments">
      <eAnnotations source="urn:org.nasdanika">
        <details key="default-feature" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Aim">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Goal" containment="true">
      <eAnnotations source="urn:org.nasdanika">
        <details key="homogenous" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
